### ISSUE TITLE
Support ledger format

### ISSUE THREAD

**Issue by pickfire** [ebcrowder/rust_ledger#16]
Is there any plan to support ledger format which is more human readable than yaml?

**Comment by ebcrowder** [comment]
Yes, I would be interested in supporting the original plaintext `ledger` format at some point. However, I do not have any near-term plans to implement it. If that is something you or anyone else reading this would like to hack on, please feel free to make a contribution.

When I started on this project, I made the decision to not use the original ledger format because I wanted to experiment with something like JSON, YAML, TOML, etc to express transactions in a more descriptive way. Each of those file formats are capable of expressing data in a variety of ways and wanted to explore that a bit more. I personally find the YAML format that `rust_ledger` uses to be quite minimal and readable, but everyone has their preferences. 

There are a lot of rewrites of `ledger` out there and almost all of them use the same plaintext format and I understand why they do. However, I wanted to take a different approach and rethink how the data is arranged. This project is more a less an experiment in that regard.

**Comment by pickfire** [comment]
I don't think you need to implement it yourself. There is one parser available already. https://github.com/marek-g/rust-ledger-parser/

Currently I am serializing the output myself. https://github.com/pickfire/fs-ledger
